apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: frontend-selector
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "nginx:1.17.3"
      nodeSelector:
        type: prod