apiVersion: v1
kind: Pod
metadata:
  name: my-liveness-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Welcome to Kubernetes! && sleep 3600']
    livenessProbe:
      exec:
        command:
        - echo
        - testing pod liveness
      initialDelaySeconds: 5
      periodSeconds: 5